_config/lib: !include "../config/hpack-common.yaml"

name:       luna-path
version:    "0.1"
author:     Jean-Christophe Mincke <jeanchristophe.mincke@gmail.com>
maintainer:
    - Jean-Christophe Mincke <jeanchristophe.mincke@gmail.com>

library:
    source-dirs:
        - src
    dependencies:
        - base
        - exceptions
        - path
        - path-io
        - filepath



tests:
    spec:
        main: Main.hs
        source-dirs: test/spec
        dependencies:
            - bytestring
            - hspec
            - hspec-jenkins
            - luna-ci
            - luna-package
            - luna-yaml-utils
            - megaparsec
            - open-browser
            - temporary-rc



