[package]
name = "enso-parser-bridge"
version = "0.1.0"
authors = ["Enso Team <contact@enso.org>"]
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]
ast = { path = "../ast/impl" }
enso-parser = { path = "../../../../lib/rust/parser" }
enso-prelude = { path = "../../../../lib/rust/prelude" }
enso-profiler = { path = "../../../../lib/rust/profiler" }
uuid = { version = "0.8", features = ["serde", "v5", "wasm-bindgen"] }
