clone:
  recursive: true
build:
  image: lunalang/buildenv-deps:v20160412
  commands:
    - date
    - scripts/gencabal
    - scripts/build --nightly compiler
    - date

notify:
  slack:
    webhook_url: $$SLACK_URL
    username: "luna: $$BRANCH"
    channel: "#cd"
    on_started: false
    on_success: true
    on_failure: true
    template: "<{{ system.link_url }}/{{ repo.full_name }}/{{ build.number }}|build #{{ build.number}}>: *{{ build.status }}* by {{ build.author }}: <https://bitbucket.org/{{ repo.full_name }}/commits/$$COMMIT|$${COMMIT:0:7}>\n\n{{ build.message }}"
