clone:
  recursive: true
build:
  image: lunalang/buildenv:alpine-8.0
  auth_config:
    username:  $$DOCKERHUB_USER
    password:  $$DOCKERHUB_PASS
    email: $$DOCKERHUB_EMAIL
  commands:
    - date
    - toolchain/scripts/gencabal
    - apk add python3
    - cd compiler
    - export PATH=$PATH:$DRONE_DIR/toolchain/HaskellBooster/preprocessor
    - stack build --stack-yaml build/stack-nightly.yaml
    - date

notify:
  slack:
    webhook_url: $$SLACK_URL
    username: "luna: $$BRANCH"
    channel: "#cd"
    on_started: false
    on_success: true
    on_failure: true
    template: "<{{ system.link_url }}/{{ repo.full_name }}/{{ build.number }}|build #{{ build.number}}>: *{{ build.status }}* by {{ build.author }}: <https://bitbucket.org/{{ repo.full_name }}/commits/$$COMMIT|$${COMMIT:0:7}>\n\n{{ build.message }}"
