overrides:
  - files:
      - "*.[j|t]s"
      - "*.[j|t]sx"
      - "*.m[j|t]s"
      - "*.c[j|t]s"
    options:
      plugins: ["prettier-plugin-organize-imports"]
      semi: false
      tabWidth: 2
      singleQuote: true
      printWidth: 100
      trailingComma: "all"
      arrowParens: "avoid"
      organizeImportsSkipDestructiveCodeActions: true
      experimentalTernaries: true

  - files: "*.md"
    options:
      printWidth: 80
      proseWrap: "always"
