[workspace]

members = [
    "app/gui",
    "build/rust-scripts",
    "lib/rust/*",
    "lib/rust/not-used/*",
    "integration-test"
]

exclude = ["lib/rust/not-used"]

default-members = ["app/gui", "lib/rust/*"]

[profile.dev]
opt-level = 0
lto = false
debug = true
debug-assertions = true

[profile.release]
opt-level = 3
lto = true
debug = false
debug-assertions = false

[profile.bench]
opt-level = 3
lto = true
debug = false
debug-assertions = false

[profile.test]
opt-level = 0
lto = false
debug = true
debug-assertions = true

[profile.integration-test]
inherits = "test"
opt-level = 2
