[workspace]

members = [
    "gui/src/rust/build",
    "gui/src/rust/ide",
    "gui/src/rust/ide/controller",
    "gui/src/rust/ide/controller/double-representation",
    "gui/src/rust/ide/controller/engine-model",
    "gui/src/rust/ide/controller/engine-protocol",
    "gui/src/rust/ide/lib/config",
    "gui/src/rust/ide/lib/ast/impl",
    "gui/src/rust/ide/lib/ast/macros",
    "gui/src/rust/ide/lib/json-rpc",
    "gui/src/rust/ide/lib/parser",
    "gui/src/rust/ide/lib/span-tree",
    "gui/src/rust/ide/lib/span-tree/example",
    "gui/src/rust/ide/view",
    "gui/src/rust/ide/view/graph-editor",
    "gui/src/rust/lib/eval-tt",
    "gui/src/rust/lib/system/web",
    "lib/rust/callback",
    "lib/rust/code-builder",
    "lib/rust/frp",
    "lib/rust/fuzzly",
    "lib/rust/types",
    "lib/rust/config-reader",
    "lib/rust/ensogl",
    "lib/rust/ensogl/example",
    "lib/rust/ensogl/lib/core",
    "lib/rust/ensogl/lib/components",
    "lib/rust/ensogl/lib/theme",
    "lib/rust/ensogl/lib/text/embedded-fonts",
    "lib/rust/ensogl/lib/text/msdf-sys",
    "lib/rust/ensogl/lib/text",
    "lib/rust/ensogl/lib/web",
    "lib/rust/launcher-shims",
    "lib/rust/automata",
    "lib/rust/data",
    "lib/rust/parser",
    "lib/rust/parser/ast",
    "lib/rust/parser/flexer",
    "lib/rust/parser/flexer-testing/definition",
    "lib/rust/parser/flexer-testing/generation",
    "lib/rust/parser/lexer/definition",
    "lib/rust/parser/lexer/generation",
    "lib/rust/parser/parser-jni",
    "lib/rust/generics",
    "lib/rust/parser/lazy-reader",
    "lib/rust/logger",
    "lib/rust/macro-utils",
    "lib/rust/optics",
    "lib/rust/prelude",
    "lib/rust/shapely/impl",
    "lib/rust/shapely/macros",
    "lib/rust/shortcuts",
    "lib/rust/shortcuts/example",
]

[profile.dev]
opt-level = 0
lto = false
debug = true
debug-assertions = true

[profile.release]
opt-level = 3
lto = true
debug = false
debug-assertions = false

[profile.bench]
opt-level = 3
lto = true
debug = false
debug-assertions = false

[profile.test]
opt-level = 0
lto = false
debug = true
debug-assertions = true
