[package]
name = "enso-profiler-data-tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enso-profiler = { path = "../../../lib/rust/profiler"}
serde = { version = "1" }

