[package]
name = "double-representation"
version = "0.1.0"
authors = ["Enso Team <contact@enso.org>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ast = { version = "0.1.0", path = "../../lib/ast/impl" }
enso-protocol = { version = "0.1.0", path = "../../lib/enso-protocol" }
parser = { version = "0.1.0", path = "../../lib/parser" }
utils = { version = "0.1.0", path = "../../lib/utils" }
enso-data = { version = "0.2.0" }
enso-logger  = { version = "0.3.1" }
enso-prelude = { version = "0.2.6" }
failure = { version = "0.1.6" }
itertools = { version = "0.10.0" }
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "0.8", features = ["serde", "v4", "wasm-bindgen"] }

[dev-dependencies]
regex = { version = "1.3.6" }
wasm-bindgen-test = { version = "0.3.8" }
