version: 2
jobs:
  luna-compiler:
    environment:
      GHC_RTS: -M3G
      LUNA_LIBS_PATH: /root/project/stdlib
    docker:
      - image: lunalang/luna-ci
    steps:
      - checkout
      - restore-cache:
          key: stack-v1-{{ checksum "config/snapshot.yaml" }}
      - run: stack setup
      - run: stack build -j1 --fast --ghc-options="-pgmc gcc-8" --test --copy-bins
      - save-cache:
          key: stack-v1-{{ checksum "config/snapshot.yaml" }}
          when: always
          paths:
              - "~/.stack"
              - ".stack-work"

      # TODO: Building optimized luna is too requiring for CircleCI... 
      # (time and memory limits on containers versus our insane requirements...)
      # Unfortunately using unoptimized luna to run tests is too slow as well.
      # Command below is to be restored after this issue is fixed and tests do pass.
      # - run: LD_PRELOAD=/root/.stack/programs/x86_64-linux/ghc-8.4.4/lib/ghc-8.4.4/rts/libffi.so.7 /root/project/dist/bin/public/luna/luna run --target=/root/project/stdlib/StdTest

workflows:
  version: 2
  percommit:
    jobs:
      - luna-compiler
