version: 2
jobs:
  luna-compiler:
    environment:
      GHC_RTS: -M3G
      LUNA_LIBS_PATH: /root/project/stdlib
    docker:
      - image: lunalang/luna-core-ci:1.0
    steps:
      - checkout
      - restore-cache:
          key: stack-v1-{{ checksum "config/snapshot.yaml" }}
      - run: stack setup
      - run: stack build -j1 --fast --ghc-options="-pgmc gcc-7" --test
      - save-cache:
          key: stack-v1-{{ checksum "config/snapshot.yaml" }}
          when: always
          paths:
              - "~/.stack"
              - ".stack-work"
      - run: /root/project/dist/bin/public/luna/luna run --target=/root/project/stdlib/StdTest

workflows:
  version: 2
  percommit:
    jobs:
      - luna-compiler
