blank_issues_enabled: false
contact_links:
  - name: Do you have a question about Enso?
    url:
    about: Ask your questions about Enso
  - name: Want to discuss Enso?
    url: https://github.com/enso-org/enso/discussions/new?category=general
    about: Talk about Enso the language
  - name: Do you have an idea?
    url: https://github.com/enso-org/enso/discussions/new?category=ideas
    about: Share your ideas for Enso
  - name: Issues with the IDE?
    url: https://github.com/enso-org/ide/issues/new/choose
    about: Please report problems with the IDE in the IDE repository
