name: luna
version: "0.1"
author: Luna Team <contact@luna-lang.org>
maintainer: Luna Team <contact@luna-lang.org>

executables:
  luna:
    main: Console.hs
    source-dirs: exe
    dependencies:
      - luna
      - open-browser

library:
    source-dirs: src
    other-modules: Paths_luna

benchmarks:
    graph-builder:
        main: Main.hs
        source-dirs: diag/bench
        dependencies:
            - criterion
            - luna

tests:
    spec:
        main: Spec.hs
        source-dirs: diag/test
        dependencies:
            - luna
            - hspec

dependencies:
    - aeson
    - base
    - bytestring
    - clock
    - constraints
    - container
    - convert
    - data-base
    - data-construction
    - data-default
    - data-layer
    - data-prop
    - data-pool
    - data-result
    - data-rtuple
    - data-shell
    - deepseq
    - dependent-state
    - digits
    - either
    - errors
    - exceptions
    - functor-utils
    - ghc
    - ghc-mtl
    - ghc-paths
    - ghc-prim
    - graphviz >= 2999.17.0.2.2
    - HTTP
    - lens
    - lens-utils
    - MissingH
    - mtl
    - network
    - OneTuple
    - placeholders
    - primitive
    - process
    - prologue
    - random
    - serialport
    - split
    - template-haskell
    - text
    - time
    - transformers
    - tuple
    - type-cache
    - typelevel
    - vector
    - visualization-api

    - reflection

default-extensions:
    - AllowAmbiguousTypes
    - ApplicativeDo
    - Arrows
    - BangPatterns
    - BinaryLiterals
    - ConstraintKinds
    - DataKinds
    - DefaultSignatures
    - DeriveDataTypeable
    - DeriveFoldable
    - DeriveFunctor
    - DeriveGeneric
    - DeriveTraversable
    - DoAndIfThenElse
    - DuplicateRecordFields
    - EmptyDataDecls
    - FlexibleContexts
    - FlexibleInstances
    - FunctionalDependencies
    - GeneralizedNewtypeDeriving
    - InstanceSigs
    - LambdaCase
    - MonadComprehensions
#    - MonadFailDesugaring
    - MultiWayIf
    - NamedWildCards
    - NegativeLiterals
    - NoImplicitPrelude
    - NumDecimals
    - OverloadedLabels
    - PackageImports
    - RankNTypes
    - RecursiveDo
    - ScopedTypeVariables
    - StandaloneDeriving
    - TemplateHaskell
    - TupleSections
    - TypeApplications
    - TypeFamilies
    - TypeFamilyDependencies
    - TypeOperators
    - ViewPatterns

    - LiberalTypeSynonyms
    - RelaxedPolyRec
