overrides:
  - files:
      - "*.[j|t]s"
      - "*.[j|t]sx"
      - "*.m[j|t]s"
      - "*.c[j|t]s"
    options:
      printWidth: 100
      tabWidth: 4
      semi: false
      singleQuote: true
      trailingComma: "es5"
      arrowParens: "avoid"
plugins:
  - "@ianvs/prettier-plugin-sort-imports"
  - prettier-plugin-tailwindcss
importOrderParserPlugins:
  - typescript
  - jsx
  - importAssertions
importOrder:
  - "^react$"
  - ""
  - "<BUILTIN_MODULES>"
  - ""
  - "<THIRD_PARTY_MODULES>"
  - ""
  - "^enso-.*$"
  - ""
  - "^[.].*/[^./]*$"
  - ""
  - "^[.]"
tailwindConfig: ./lib/dashboard/tailwind.config.cjs
