[package]
name = "rust-ffi"
version = "0.1.0"
edition = "2021"
authors = ["Enso Team <contact@enso.org>"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = { version = "0.2.84", features = [] }
enso-parser = { path = "../../../lib/rust/parser" }
serde_json = "1.0"
console_error_panic_hook = { version = "0.1.6" }

[workspace]

[profile.release]
debug = false
strip = true
lto = true
codegen-units = 1
opt-level = "z"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
# wasm-opt = ['-Os']
