[package]
name = "rust-ffi"
version = "0.1.0"
edition = "2021"
authors = ["Enso Team <contact@enso.org>"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
enso-parser = { path = "../../../lib/rust/parser" }
serde_json = { workspace = true }
wasm-bindgen = { workspace = true }

#[profile.release]
#debug = false
#strip = true
#lto = true
#codegen-units = 1
#opt-level = "z"

[package.metadata.wasm-pack.profile.release]
wasm-opt = ['-Os']
