extra-deps: [ghc-session-0.1.2.0, error-util-0.0.1.1, cond-0.4.1.1, ghc-mtl-1.2.1.0,
  serialport-0.4.7, aeson-1.0.2.1]
ghc-options: {'*': -DFastCompilation -fenable-rewrite-rules -threaded -funbox-strict-fields
    -O0 -fconstraint-solver-iterations=100}
local-bin-path: ./bin
packages:
- {location: .}
- {extra-dep: true, location: ../core}
- extra-dep: true
  location: {commit: 9d451ec9eeb06d4e28bbd66915fe1698bae2f001, git: 'https://github.com/luna/container.git'}
- extra-dep: true
  location: {commit: 6b9f0f6ec43e83c88f28e0fe051ac74516c35605, git: 'https://github.com/luna/data-pool.git'}
- extra-dep: true
  location: {commit: 5cb0cedea0c761ad3f833888f4c70c4231392316, git: 'https://github.com/luna/convert.git'}
- extra-dep: true
  location: {commit: 23a039debfd51a9b7f46b5e106feb30839960e37, git: 'https://github.com/luna/data-base.git'}
- extra-dep: true
  location: {commit: 211164cbb214790b26fb5bac7f2771d18c1b9574, git: 'https://github.com/luna/data-construction.git'}
- extra-dep: true
  location: {commit: 62aebd5ecb6ea873ce8db4cc230d156126cd82ee, git: 'https://github.com/luna/data-layer.git'}
- extra-dep: true
  location: {commit: c20f35c8e2f25fd84df385e8646b125d9fca8ac4, git: 'https://github.com/luna/data-repr.git'}
- extra-dep: true
  location: {commit: 604145037427b944050f1959bcdffc375328f72c, git: 'https://github.com/luna/data-result.git'}
- extra-dep: true
  location: {commit: 62dca5524c1fadb19339b8257809d6c872b5f82d, git: 'https://github.com/luna/dependent-state.git'}
- extra-dep: true
  location: {commit: 891b8882a5b5cb4673c36a57c3cbd55085f975cd, git: 'https://github.com/luna/functor-utils.git'}
- extra-dep: true
  location: {commit: 5dc5b731a4313e44d55677ed6b9f38456feb2d56, git: 'https://github.com/luna/impossible.git'}
- extra-dep: true
  location: {commit: 446533d1169324542c220a7fe179616759fcbd8a, git: 'https://github.com/luna/lens-utils.git'}
- extra-dep: true
  location: {commit: 53538017ad47a0a473233577595d8ac6e3eae9a0, git: 'https://github.com/luna/poly-control.git'}
- extra-dep: true
  location: {commit: 773179796be933097e3c1468c16307f8015e6a1d, git: 'https://github.com/luna/prologue.git'}
- extra-dep: true
  location: {commit: 7c9eab45f65ab98290282e11d19e39401830ab9c, git: 'https://github.com/luna/type-cache.git'}
- extra-dep: true
  location: {commit: 9165d1818d9ec0b0f030623282b80c2d654089ea, git: 'https://github.com/luna/typelevel.git'}
- extra-dep: true
  location: {commit: 211164cbb214790b26fb5bac7f2771d18c1b9574, git: 'https://github.com/luna/data-construction.git'}
- extra-dep: true
  location: {commit: adb894846d34ceaa005961bd8fe676023cf1b036, git: 'https://github.com/luna/data-prop.git'}
- extra-dep: true
  location: {commit: 0f86d4dff7192db7b4f4001f427126a889ff311f, git: 'https://github.com/luna/data-rtuple.git'}
- extra-dep: true
  location: {commit: f7124ecbfa4ce8802e3c1431e54300188616fe64, git: 'https://github.com/luna/data-shell.git'}
- extra-dep: true
  location: {commit: af5a618f5813ac639a6760836a6d6fa7ef5af1da, git: 'https://github.com/luna/visualization-api.git'}
resolver: lts-7.9
