extra-deps: [ghc-session-0.1.2.0, error-util-0.0.1.1, cond-0.4.1.1, ghc-mtl-1.2.1.0,
  serialport-0.4.7]
ghc-options: {'*': -DFastCompilation -threaded -funbox-strict-fields -O0}
local-bin-path: ./bin
packages:
- {location: .}
- {extra-dep: true, location: ../core}
- extra-dep: true
  location: {commit: faa0bb08a1273d494fec717b322534e90a1d7a00, git: 'https://github.com/wdanilo/container.git'}
- extra-dep: true
  location: {commit: 8ad8bc28bd8ce085772bbc778841b322c6c65673, git: 'https://github.com/wdanilo/data-pool.git'}
- extra-dep: true
  location: {commit: 203827783338df71a768f8025c0815dbf187f284, git: 'https://github.com/wdanilo/convert.git'}
- extra-dep: true
  location: {commit: f53b117fa0b2135d80b3a7ff5318d69aa4aa20cd, git: 'https://github.com/wdanilo/data-base.git'}
- extra-dep: true
  location: {commit: f2c0719aa07f7215dd3513ef015098465054d083, git: 'https://github.com/wdanilo/data-construction.git'}
- extra-dep: true
  location: {commit: 0a4b28829bfc18573afe1bdebde8715e77b9ee07, git: 'https://github.com/wdanilo/data-layer.git'}
- extra-dep: true
  location: {commit: 14ecd09499c6709074dd3a79c79628e327f83d9f, git: 'https://github.com/wdanilo/data-repr.git'}
- extra-dep: true
  location: {commit: db450f0f50ab7c6d743294a17f4b39c4d640a18b, git: 'https://github.com/wdanilo/data-result.git'}
- extra-dep: true
  location: {commit: 6841baeff92813c6b72788cb24c0dd7e4f1ec16a, git: 'https://github.com/wdanilo/dependent-state.git'}
- extra-dep: true
  location: {commit: 141cdf78a1ef4dca0b8b2a2bd51d1554a6afc482, git: 'https://github.com/wdanilo/functor-utils.git'}
- extra-dep: true
  location: {commit: 33a9dd04e80f52bc9682b06a295ceb1d754ea120, git: 'https://github.com/wdanilo/impossible.git'}
- extra-dep: true
  location: {commit: 37a676e1ece1a349630f907726b493b777e1a4ae, git: 'https://github.com/wdanilo/lens-utils.git'}
- extra-dep: true
  location: {commit: 1c41d3032b13afaec94c91d2b4459927687e4930, git: 'https://github.com/wdanilo/poly-control.git'}
- extra-dep: true
  location: {commit: 7c55103248b34093b9038c1d0ab17b290bb9a97f, git: 'https://github.com/wdanilo/prologue.git'}
- extra-dep: true
  location: {commit: bb6c4bcf50a4395a393920767b908d1fea517eed, git: 'https://github.com/wdanilo/type-cache.git'}
- extra-dep: true
  location: {commit: e814f29ee2e5a508c3d0b0a449f0d938be1c10ac, git: 'https://github.com/wdanilo/typelevel.git'}
- extra-dep: true
  location: {commit: f2c0719aa07f7215dd3513ef015098465054d083, git: 'https://github.com/wdanilo/data-construction.git'}
- extra-dep: true
  location: {commit: 7dd2c9adc8918334bc3ea20c94171d71a49ad10d, git: 'https://github.com/wdanilo/data-member.git'}
- extra-dep: true
  location: {commit: 925e7beba902a21452d37191c940af87bca5aea0, git: 'https://github.com/wdanilo/data-rtuple.git'}
- extra-dep: true
  location: {commit: a7d942b3f1d3bf931b6bca06a4d8cece82ff3c39, git: 'https://github.com/wdanilo/data-shell.git'}
- extra-dep: true
  location: {commit: af5a618f5813ac639a6760836a6d6fa7ef5af1da, git: 'https://bitbucket.org/NewByteOrder/visualization-api.git'}
resolver: lts-7.9
