extra-deps: [ghc-session-0.1.2.0, error-util-0.0.1.1, cond-0.4.1.1, ghc-mtl-1.2.1.0,
  serialport-0.4.7, aeson-1.0.2.1]
ghc-options: {'*': -DFastCompilation -threaded -funbox-strict-fields -O}
local-bin-path: ./bin
packages:
- {location: .}
- {extra-dep: true, location: ../core}
- {extra-dep: true, location: ../parser}
- extra-dep: true
  location: {commit: 55bfeedd2ac1ac2adf896710eff32c7d582fa049, git: 'https://github.com/wdanilo/container.git'}
- extra-dep: true
  location: {commit: 10a1f6498d0426cd9c07c59cdc5032d98e5f3097, git: 'https://github.com/wdanilo/data-pool.git'}
- extra-dep: true
  location: {commit: 3f36f8432ffeec3f563c1087d7c7197cae074a1d, git: 'https://github.com/wdanilo/convert.git'}
- extra-dep: true
  location: {commit: 2e62e4316bc56140b0e10f5226aa1ef03e92b3ca, git: 'https://github.com/wdanilo/data-base.git'}
- extra-dep: true
  location: {commit: 7d1beb463586b883812f6e7febce95126dfb9f65, git: 'https://github.com/wdanilo/data-construction.git'}
- extra-dep: true
  location: {commit: adac5a65fbfa3f4ac06b1a15a3c745ac7d14b37c, git: 'https://github.com/wdanilo/data-layer.git'}
- extra-dep: true
  location: {commit: 3196f5f7659d45064ea8a44748fc2378d23688d7, git: 'https://github.com/wdanilo/data-repr.git'}
- extra-dep: true
  location: {commit: fd76b8e185cc46ef5476aa522655e17cd24f23d5, git: 'https://github.com/wdanilo/data-result.git'}
- extra-dep: true
  location: {commit: c3d2f262831072029bbf50c43559d97f1b1e0602, git: 'https://github.com/wdanilo/dependent-state.git'}
- extra-dep: true
  location: {commit: d3300a6ae3f5676c7251320e635e2ce3828343c5, git: 'https://github.com/wdanilo/functor-utils.git'}
- extra-dep: true
  location: {commit: c0f1980a9463c51b04c146c6c96e982e8228d669, git: 'https://github.com/wdanilo/impossible.git'}
- extra-dep: true
  location: {commit: b4267bb5e7c79de78ebea1f9a788aecbf1cc5cce, git: 'https://github.com/wdanilo/lens-utils.git'}
- extra-dep: true
  location: {commit: a4188812a30426a622774b0fc97af66594a9e166, git: 'https://github.com/wdanilo/poly-control.git'}
- extra-dep: true
  location: {commit: a76074e8efda50f71827e7955710a619fbd7c898, git: 'https://github.com/wdanilo/prologue.git'}
- extra-dep: true
  location: {commit: 31bbc071c55bab984f4eb04ba658955160f22a09, git: 'https://github.com/wdanilo/type-cache.git'}
- extra-dep: true
  location: {commit: 864908b8159f463be2bac09b193550683c084a7b, git: 'https://github.com/wdanilo/typelevel.git'}
- extra-dep: true
  location: {commit: 7d1beb463586b883812f6e7febce95126dfb9f65, git: 'https://github.com/wdanilo/data-construction.git'}
- extra-dep: true
  location: {commit: f4da8f18b3af7ed55f8df399e1d3b2be6230f6ac, git: 'https://github.com/wdanilo/data-prop.git'}
- extra-dep: true
  location: {commit: 322832548ab9b39298d581b247356d227f2acaf7, git: 'https://github.com/wdanilo/data-rtuple.git'}
- extra-dep: true
  location: {commit: d39b132bd34295df8e987f5bc25f59b3c7f67ee1, git: 'https://github.com/wdanilo/data-shell.git'}
- extra-dep: true
  location: {commit: af5a618f5813ac639a6760836a6d6fa7ef5af1da, git: 'https://bitbucket.org/NewByteOrder/visualization-api.git'}
resolver: lts-7.9
