_config/lib: !include "../config/hpack-common.yaml"

name:       luna-playground
version:    "0.1"
author:     Luna Team <contact@luna-lang.org>
maintainer: Luna Team <contact@luna-lang.org>

executables:
  lunapg:
    main: Main.hs
    source-dirs: src
    ghc-options: -threaded "-with-rtsopts=-N -T"
    dependencies:
      - async
      - base
      - layouting
      - luna-core
      - luna-passes
      - luna-package
      - luna-runtime
      - luna-stdlib
      - luna-syntax-text-lexer
      - luna-syntax-text-model
      - luna-syntax-text-parser
      - time
      - open-browser
      - containers
      - unordered-containers
      - aeson
      - MissingH
      - bytestring
      - mtl
      - reflection
      - directory
      - path >= 0.6.0
      - bimap
      - optparse-applicative
      - terminal-text
      - text
      - ansi-wl-pprint
      - executable-path
      - filepath
      - prologue
      - layered-state
      - luna-cpp-containers
      - luna-data-tag
      - luna-debug
      - luna-memory-manager

default-extensions: *luna-extensions

