# This file is manually managed. It is used to upload benchmarks to to the
# https://github.com/enso-org/engine-benchmark-results repository.

name: Benchmarks upload
on:
  pull_request:
    branches: ["*"]
  schedule:
    # Run every day at 5:30 AM. At midnight, benchmarks run, and we want this job to be
    # scheduled after all the benchmarks are finished, so that we have the newest results.
    - cron: 30 5 * * *
jobs:
  upload-benchmarks:
    name: Upload benchmarks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout enso repository
        uses: actions/checkout@v4
        with:
          repository: enso-org/enso
          path: enso
      - name: Checkout engine-benchmark-results repository
        uses: actions/checkout@v4
        with:
          repository: enso-org/engine-benchmark-results
          path: engine-benchmark-results
          token: ${{ secrets.ENSO_BENCHMARK_RESULTS_TOKEN }}
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3 \
            python3-jinja2 \
            python3-numpy \
            python3-pandas
          sudo apt-get install -y gh
      - name: Set up git
        run: |
          cd ${{ github.workspace }}/engine-benchmark-results
          git config --global user.email "ci@enso.org"
          git config --global user.name "Enso CI Bot"
          echo "Hello world" > hello.txt
          git add hello.txt
          git commit -m "Add hello.txt"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          directory: engine-benchmark-results
          github_token: ${{ secrets.ENSO_BENCHMARK_RESULTS_TOKEN }}

      #- name: Upload benchmarks
        #run: |
          #cd enso/tools/performance/engine-benchmarks
          #python3 website_regen.py \
          #  -v \
          #  --local-repo  ${{ github.workspace }}/engine-benchmark-results
        #env:
        #  GITHUB_TOKEN: ${{ secrets.ENSO_BENCHMARK_RESULTS_TOKEN }}
