name: Package Tools
on:
  push: {}
  workflow_dispatch: {}
jobs:
  run-create:
    name: Run create
    runs-on:
    - Linux
    steps:
    - if: runner.os == 'Windows'
      name: Workaround for https://github.com/actions/checkout/issues/590 (Windows)
      run: '"c:\Program Files\Git\bin\bash.exe" -c "git checkout -f $(git -c user.name=x -c user.email=x@x commit-tree $(git hash-object -t tree /dev/null) < /dev/null) || :"'
      shell: cmd
    - if: runner.os != 'Windows'
      name: Workaround for  https://github.com/actions/checkout/issues/590 (non-Windows)
      run: 'git checkout -f $(git -c user.name=x -c user.email=x@x commit-tree $(git hash-object -t tree /dev/null) < /dev/null) || :'
      shell: bash
    - name: Checking out the repository
      uses: actions/checkout@v2
      with:
        repository: enso-org/shader-tools
        clean: false
        submodules: recursive
    - id: step_0
      run: cargo run --package enso-shader-tools --bin create
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      timeout-minutes: 360
    outputs:
      ENSO_RELEASE_ID: ${{ steps.step_0.outputs.ENSO_RELEASE_ID }}
    timeout-minutes: 360
  run-package:
    name: Run package
    needs:
    - run-create
    runs-on:
    - macOS
    steps:
    - if: runner.os == 'Windows'
      name: Workaround for https://github.com/actions/checkout/issues/590 (Windows)
      run: '"c:\Program Files\Git\bin\bash.exe" -c "git checkout -f $(git -c user.name=x -c user.email=x@x commit-tree $(git hash-object -t tree /dev/null) < /dev/null) || :"'
      shell: cmd
    - if: runner.os != 'Windows'
      name: Workaround for  https://github.com/actions/checkout/issues/590 (non-Windows)
      run: 'git checkout -f $(git -c user.name=x -c user.email=x@x commit-tree $(git hash-object -t tree /dev/null) < /dev/null) || :'
      shell: bash
    - name: Checking out the repository
      uses: actions/checkout@v2
      with:
        repository: enso-org/shader-tools
        clean: false
        submodules: recursive
    - run: cargo run --package enso-shader-tools --bin package
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      timeout-minutes: 360
    env:
      ENSO_RELEASE_ID: ${{ needs.run-create.outputs.ENSO_RELEASE_ID }}
    timeout-minutes: 360
  run-publish:
    name: Run publish
    needs:
    - run-create
    - run-package
    runs-on:
    - Linux
    steps:
    - if: runner.os == 'Windows'
      name: Workaround for https://github.com/actions/checkout/issues/590 (Windows)
      run: '"c:\Program Files\Git\bin\bash.exe" -c "git checkout -f $(git -c user.name=x -c user.email=x@x commit-tree $(git hash-object -t tree /dev/null) < /dev/null) || :"'
      shell: cmd
    - if: runner.os != 'Windows'
      name: Workaround for  https://github.com/actions/checkout/issues/590 (non-Windows)
      run: 'git checkout -f $(git -c user.name=x -c user.email=x@x commit-tree $(git hash-object -t tree /dev/null) < /dev/null) || :'
      shell: bash
    - name: Checking out the repository
      uses: actions/checkout@v2
      with:
        repository: enso-org/shader-tools
        clean: false
        submodules: recursive
    - run: cargo run --package enso-shader-tools --bin publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      timeout-minutes: 360
    env:
      ENSO_RELEASE_ID: ${{ needs.run-create.outputs.ENSO_RELEASE_ID }}
    timeout-minutes: 360
env:
  ENSO_BUILD_SKIP_VERSION_CHECK: 'true'
